services:
  web:
    build: .
    command: gunicorn ctfwiki.wsgi:application --bind 0.0.0.0:9111 --workers 3 --worker-class gevent --timeout 120
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "9111:9111"
    depends_on:
      - db
    restart: always  # Agar otomatis restart jika crash

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ctfwiki
      POSTGRES_USER: ctfwikiuser
      POSTGRES_PASSWORD: ctfwikipass
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: